logLevel = "INFO"

################################################################
# Entrypoints configuration
################################################################
defaultEntryPoints = ["https","http"]

[entryPoints]
    #[entryPoints.insn]
    #address = ":10255"
    [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
    [entryPoints.traefik]
    address = ":8081"

[acme]
email = "karsten@karstenjakobsen.dk"
storage = "traefik/acme/account"
onHostRule = true
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "karstenjakobsen.dk"
  sans = ["kogsbolle-1.karstenjakobsen.dk","kogsbolle-2.karstenjakobsen.dk","www.karstenjakobsen.dk"]

################################################################
# Access logs configuration
################################################################

[accessLog]

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]


################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

################################################################
# Enable Consul KV Provider.
################################################################
[consul]

# Consul server endpoint.
#
# Required
# Default: "127.0.0.1:8500"
#
endpoint = "consul.service.consul:8500"

# Enable watch Consul changes.
#
# Optional
# Default: true
#
watch = true

# Prefix used for KV store.
#
# Optional
# Default: traefik
#
prefix = "traefik"

################################################################
# Consul Catalog configuration backend
################################################################

# Enable Consul Catalog configuration backend.
[consulCatalog]

endpoint = "consul.service.consul:8500"

prefix = "traefik"

constraints = ["tag==service"]